sudo: false

language: rust

# cache: cargo

# trigger on pushes to master branch
branches:
  only:
   - master

#Specify multiple parallel jobs. 
#This could be done by a matrix expands rust x BOARD x EG, but
#I cannot figure out how to do a matrix expand with two env variables.

rust:
  - stable
#  - nightly

##jobs:
matrix:
    #allow_failures:
    #   - rust: nightly

    #fast_finish: true

    include:
        - name: "bluepill"
          env: BOARD="bluepill"

        - name: "discovery-stm32l100"
          env: BOARD="discovery-stm32l100"

before_install:
  - if [[ "$BOARD" = "bluepill" ]]; then
       export MCU="stm32f103" TARGET="thumbv7m-none-eabi" ;
    fi

  - if [[ "$BOARD" = "discovery-stm32l100" ]]; then
       export MCU="stm32l100" TARGET="thumbv7m-none-eabi" ;
    fi

  - echo  BOARD= ${BOARD} TARGET= ${TARGET}  MCU= ${MCU}
  - echo  EG= ${EG}

install:
  - rustup target add ${TARGET}
  - echo  PWD= ${PWD}
  - cd  boards/${BOARD}
  - cargo build  --target ${TARGET}

script:
  - echo BOARD= ${BOARD} TARGET= ${TARGET}  MCU= ${MCU}  EG= ${EG}
  # verify this is already in boards/${BOARD} from install
  - echo  PWD= ${PWD}
  - cargo build  --target ${TARGET}  --features ${MCU}  --example blink
  - cargo build  --target ${TARGET}  --features ${MCU}  --example serial_loopback_char
