sudo: false

language: rust

cache: boards/*/target

# trigger on pushes to master branch
branches:
  only:
   - master

#Specify multiple parallel jobs. 
#This could be done by a matrix expands rust x BOARD x EG, but
#I cannot figure out how to do a matrix expand with two env variables.

rust:
  - stable
#  - nightly

env:
  global:
    - EG=blink
    - EG=serial_loopback_char

##jobs:
matrix:
    #allow_failures:
    #   - rust: nightly

    fast_finish: true

    include:
        - name: "bluepill maybe blink"
          rust: stable
          env: MCU="stm32f103"  TARGET="thumbv7m-none-eabi"  BOARD="bluepill"

        - name: "discovery-stm32l100 maybe blink"
          rust: stable
          env: MCU="stm32l100"  TARGET="thumbv7m-none-eabi"  BOARD="discovery-stm32l100"

before_install:

  #- if [[ "$MCU" = "stm32f103" ]]; then
  #     export TARGET="thumbv7m-none-eabi"  BOARD="bluepill";
  # fi

  - echo  BOARD= ${BOARD} target= ${TARGET}  features= ${MCU}
  - echo  example= ${EG}

install:
  - rustup target add ${TARGET}
  - echo  PWD= ${PWD}
  - cd boards/${BOARD} 
  - cargo build  --target ${TARGET}

script:
  - echo BOARD= ${BOARD} TARGET= ${TARGET}  MCU= ${MCU}  EG= ${EG}
  - echo  PWD= ${PWD}
  - ls boards
  - cd boards/${BOARD} 
  - cargo build  --target ${TARGET}  --features ${MCU}  --example ${EG}
