sudo: false

language: rust

# cache: cargo

# trigger on pushes to master branch
branches:
  only:
   - master

#Specify multiple parallel jobs. 
#This could be done by a matrix expands rust x BOARD x EG, but
#I cannot figure out how to do a matrix expand with two env variables.

rust:
  - stable
#  - nightly

##jobs:
matrix:
    #allow_failures:
    #   - rust: nightly

    #fast_finish: true

    include:
        - name: "bluepill"
          env: MCU="stm32f103"  TARGET="thumbv7m-none-eabi"  BOARD="bluepill"

        - name: "none-stm32f100"
          env: MCU="stm32f100"  TARGET="thumbv7m-none-eabi"  BOARD="none"

        #- name: "discovery-stm32l100"
        #  env: MCU="stm32l100"  TARGET="thumbv7m-none-eabi"  BOARD="discovery-stm32l100"

        - name: "discovery-stm32f303"
          env: MCU="stm32f303"  TARGET="thumbv7em-none-eabihf"  BOARD="discovery-stm32f303"

        - name: "nucleo-64"
          env: MCU="stm32f411"  TARGET="thumbv7em-none-eabihf"  BOARD="nucleo-64"


        #- name: "heltec-lora-node151"
        #  env: MCU="stm32l151"  TARGET="thumbv7m-none-eabi"  BOARD="heltec-lora-node151"

before_install:
  - rustup target add ${TARGET}

install:
  - cd  boards/${BOARD}
  - cargo update
  - cargo build  --target ${TARGET}  --features ${MCU}

script:
  # verify this is already in boards/${BOARD} from install
  - echo  PWD= ${PWD}
  - echo BOARD= ${BOARD} TARGET= ${TARGET}  MCU= ${MCU}
  - cargo build  --target ${TARGET}  --features ${MCU}  --example blink
  - cargo build  --target ${TARGET}  --features ${MCU}  --example echo_by_char
  - cargo build  --target ${TARGET}  --features ${MCU}  --example  serial_cross
  # - cargo build  --target ${TARGET}  --features ${MCU}  --example  serial_dma_tx
  - cargo build  --target ${TARGET}  --features ${MCU}  --example  serial_fmt
  - cargo build  --target ${TARGET}  --features ${MCU}  --example  serial_gps_rw_by_char
  - cargo build  --target ${TARGET}  --features ${MCU}  --example  serial_gps_rw
  - cargo build  --target ${TARGET}  --features ${MCU}  --example  serial_loopback_char
  - cargo build  --target ${TARGET}  --features ${MCU}  --example  serial_loopback_string
  - cargo build  --target ${TARGET}  --features ${MCU}  --example  serial_pass_thru_string
