sudo: false

language: rust

cache: boards/*/target

# trigger on pushes to master branch
branches:
  only:
   - master

#specify multiple parallel jobs. matrix expands rust x BOARD x EG
rust:
  - stable
#  - nightly

env:
  global:
    - EG=blink
    - EG=serial_loopback_char

##matrix:
jobs:
    #allow_failures:
    #   - rust: nightly

    fast_finish: true

    include:
        - name: "bluepill maybe blink"
          rust: stable
          env: MCU="stm32f103"  TARGET="thumbv7m-none-eabi" BOARD="bluepill"

    include:
        - name: "discovery-stm32l100 maybe blink"
          rust: stable
          env: MCU="stm32l100"  TARGET="thumbv7m-none-eabi" BOARD="discovery-stm32l100"

before_install:

  #- if [[ "$MCU" = "stm32f103" ]]; then
  #     export TARGET="thumbv7m-none-eabi"  BOARD="bluepill";
  # fi

  - echo  BOARD= ${BOARD} target= ${TARGET}  features= ${MCU}
  - echo  example= ${EG}

install:
  - rustup target add ${TARGET}
  - cd boards/${BOARD} 
  - cargo build  --target ${TARGET}

script:
  - echo BOARD= ${BOARD} TARGET= ${TARGET}  MCU= ${MCU}  EG= ${EG}
  - cd boards/${BOARD} 
  - cargo build  --target ${TARGET}  --features ${MCU}  --example ${EG}
