sudo: false

language: rust

# cache: cargo

# trigger on pushes to master branch
branches:
  only:
   - master

#Specify multiple parallel jobs. 
#This could be done by a matrix expands rust x BOARD 

rust:
  - stable
#  - nightly

##jobs:
matrix:
    #allow_failures:
    #   - rust: nightly

    #fast_finish: true

    include:
        - name: "bluepill"
          env: HAL="stm32f1xx"  MCU="stm32f103"  TARGET="thumbv7m-none-eabi"     BOARD="bluepill"

        #- name: "none-stm32f100"
        #  env: HAL="stm32f1xx"  MCU="stm32f100"  TARGET="thumbv7m-none-eabi"     BOARD="none-stm32f100"

        #- name: "none-stm32f101"
        #  env: HAL="stm32f1xx"  MCU="stm32f101"  TARGET="thumbv7m-none-eabi"     BOARD="none-stm32f101"

        - name: "discovery-stm32f303"
          env: HAL="stm32f3xx"  MCU="stm32f303xc" TARGET="thumbv7em-none-eabihf"  BOARD="discovery-stm32f303"

        - name: "nucleo-64"
          env: HAL="stm32f4xx"  MCU="stm32f411"  TARGET="thumbv7em-none-eabihf"  BOARD="nucleo-64"

        - name: "blackpill-stm32f411"
          env: HAL="stm32f4xx"  MCU="stm32f411"  TARGET="thumbv7em-none-eabihf"  BOARD="blackpill-stm32f411"

        - name: "blackpill-stm32f401"
          env: HAL="stm32f4xx"  MCU="stm32f401"  TARGET="thumbv7em-none-eabihf"  BOARD="blackpill-stm32f401"

        - name: "discovery-stm32l100"
          env: HAL="stm32l1xx"  MCU="stm32l100"  TARGET="thumbv7m-none-eabi"     BOARD="discovery-stm32l100"

        - name: "heltec-lora-node151"
          env: HAL="stm32l1xx"  MCU="stm32l151"  TARGET="thumbv7m-none-eabi"     BOARD="heltec-lora-node151"

before_install:
  - rustup target add ${TARGET}

install:
  - export PATH="${PWD}/utils:$PATH"  # for checkExample script
  - export UTILS="${PWD}/utils"       # for png files copied in checkExample script
  - cd  boards/${BOARD}
  - cargo update
  - cargo build  --target ${TARGET}  --features ${HAL},${MCU}

script:
  # verify this is already in boards/${BOARD} from install
  - echo  PWD= ${PWD}
  - echo BOARD= ${BOARD} TARGET= ${TARGET}  HAL= ${HAL} MCU= ${MCU}
  #- cargo build  --target ${TARGET}  --features ${HAL},${MCU}  --example  blink
  - checkExample  blink
  - checkExample  blink3
  - checkExample  echo_by_char
  - checkExample  echo_string
  - checkExample  serial_char
  - checkExample  serial_string
  - checkExample  gps_rw_by_char
  - checkExample  gps_rw

  - checkExample  temperature

  - checkExample  dht
  - checkExample  dht11
  - checkExample  text_i2c
  - checkExample  oled_gps
  #- checkExample  ads1015-display
  - checkExample  lora_send
  - checkExample  lora_receive
  - checkExample  lora_gps

  - echo  PWD= ${PWD}
  # next also ensure there is something new to commit, so commit does not fail
  - date >examplesNewStatus/DATE.STAMP
  - echo ${TRAVIS_COMMIT} > examplesNewStatus/COMMIT

  - ls examplesNewStatus
  - cd  ../../../
  - echo  PWD= ${PWD}
  - mv eg_stm_hal eg_stm_hal_master

  # The travis start up only cloned master, now gh-pages is needed. 
  # Note this is a separate clone, not a branch of the original clone.
  # Travis must enable token use for master since this build is started by a master commit,
  # even though the token is only needed to allow the gh-pages push.
 
  - git clone --depth=50 --branch=gh-pages https://${GITHUB_TOKEN}@github.com/pdgilbert/eg_stm_hal.git

  - mkdir -p eg_stm_hal/examplesStatus/${BOARD}
  - mv eg_stm_hal_master/boards/${BOARD}/examplesNewStatus/*  eg_stm_hal/examplesStatus/${BOARD}
  - cd eg_stm_hal
  - git status
  - ls examplesStatus/${BOARD}

  - git add examplesStatus/${BOARD} 
  - git commit -m "commiting new examplesStatus/${BOARD}."
  - git status 
  - git push  
  - echo  pushed examplesStatus/${BOARD} on gh-pages branch
