sudo: false

language: rust

# cache: cargo

# trigger on pushes to master branch
branches:
  only:
   - master

#Specify multiple parallel jobs. 
#This could be done by a matrix expands rust x BOARD 

rust:
  - stable
#  - nightly

##jobs:
matrix:
    #allow_failures:
    #   - rust: nightly

    #fast_finish: true

    include:
        - name: "bluepill"
          env: HAL="stm32f1xx"  MCU="stm32f103"  TARGET="thumbv7m-none-eabi"     BOARD="bluepill"

        #- name: "none-stm32f100"
        #  env: HAL="stm32f1xx"  MCU="stm32f100"  TARGET="thumbv7m-none-eabi"     BOARD="none-stm32f100"

        #- name: "none-stm32f101"
        #  env: HAL="stm32f1xx"  MCU="stm32f101"  TARGET="thumbv7m-none-eabi"     BOARD="none-stm32f101"

        - name: "discovery-stm32f303"
          env: HAL="stm32f3xx"  MCU="stm32f303xc" TARGET="thumbv7em-none-eabihf"  BOARD="discovery-stm32f303"

        - name: "nucleo-64"
          env: HAL="stm32f4xx"  MCU="stm32f411"  TARGET="thumbv7em-none-eabihf"  BOARD="nucleo-64"

        - name: "discovery-stm32l100"
          env: HAL="stm32l1xx"  MCU="stm32l100"  TARGET="thumbv7m-none-eabi"     BOARD="discovery-stm32l100"

        - name: "heltec-lora-node151"
          env: HAL="stm32l1xx"  MCU="stm32l151"  TARGET="thumbv7m-none-eabi"     BOARD="heltec-lora-node151"

before_install:
  - rustup target add ${TARGET}

install:
  - cd  boards/${BOARD}
  - cargo update
  - cargo build  --target ${TARGET}  --features ${HAL},${MCU}

script:
  # verify this is already in boards/${BOARD} from install
  - echo  PWD= ${PWD}
  - echo BOARD= ${BOARD} TARGET= ${TARGET}  HAL= ${HAL} MCU= ${MCU}
  - cargo build  --target ${TARGET}  --features ${HAL},${MCU}  --example  blink3
  - cargo build  --target ${TARGET}  --features ${HAL},${MCU}  --example  echo_console_by_char
  - cargo build  --target ${TARGET}  --features ${HAL},${MCU}  --example  echo_console_string
  - cargo build  --target ${TARGET}  --features ${HAL},${MCU}  --example  serial_char
  - cargo build  --target ${TARGET}  --features ${HAL},${MCU}  --example  serial_string
  - cargo build  --target ${TARGET}  --features ${HAL},${MCU}  --example  gps_rw_by_char
  - cargo build  --target ${TARGET}  --features ${HAL},${MCU}  --example  gps_rw

  - cargo build  --target ${TARGET}  --features ${HAL},${MCU}  --example  temperature

  - cargo build  --target ${TARGET}  --features ${HAL},${MCU}  --example  dht
  - cargo build  --target ${TARGET}  --features ${HAL},${MCU}  --example  dht11
  - cargo build  --target ${TARGET}  --features ${HAL},${MCU}  --example  ads1015-display
