sudo: false

language: rust

cache: cargo

# trigger on pushes to master branch
branches:
  only:
   - master

#specify multiple parallel jobs. matrix expands rust x MCU x EG
rust:
  - stable
#  - nightly

env:
- MCU=stm32f103
- MCU=stm32l100

env:
- EG=blink
- EG=serial_loopback_char

##matrix:
#jobs:
#    #  allow_failures:
#    #    - rust: nightly
#    #  fast_finish: true
#    include:
#        - name: "bluepill blink"
#          rust: stable
#          EG: blink
#          env: MCU="stm32f103"  TARGET="thumbv7m-none-eabi" 
#
#    include:
#        - name: "bluepill serial_loopback_char"
#          rust: stable
#          EG: serial_loopback_char
#          env: MCU="stm32f103"  TARGET="thumbv7m-none-eabi" 
#
#    include:
#        - name: "discovery-stm32l100 blink"
#          rust: stable
#          EG: blink
#          env: MCU="stm32l100"  TARGET="thumbv7m-none-eabi" 

before_install:

  - if [[ "$MCU" = "stm32f103" ]]; then
       export TARGET="thumbv7m-none-eabi" ;
   fi

  - if [[ "$MCU" = "stm32l100" ]]; then
       export TARGET="thumbv7m-none-eabi" ;
   fi

  - echo  target is ${TARGET}  features is ${MCU}  example is ${EG}

install:
  - rustup target add ${TARGET}
  - cargo build  --target ${TARGET}

script:
  - echo  target is ${TARGET}  features is ${MCU}  example is ${EG}
  - cargo build  --target ${TARGET}  --features ${MCU}  --example ${EG}
