sudo: false

language: rust

rust:
  - stable
#  - nightly

cache: cargo

# trigger on pushes to master branch
branches:
  only:
   - master

env:
- MCU=stm32f103
- MCU=stm32f101
- MCU=stm32f100

#specify multiple parallel jobs. matrix could be MCU x EG
matrix:
    #  allow_failures:
    #    - rust: nightly
    #  fast_finish: true
    include:
        - name: "bluepill blink"
          rust: stable
          EG: blink
          env: MCU="stm32f103"  TARGET="thumbv7m-none-eabi" 

    include:
        - name: "bluepill serial_loopback_char"
          rust: stable
          EG: serial_loopback_char
          env: MCU="stm32f103"  TARGET="thumbv7m-none-eabi" 

    include:
        - name: "discovery-stm32l100 blink"
          rust: stable
          EG: blink
          env: MCU="stm32l100"  TARGET="thumbv7m-none-eabi" 


install:
  - rustup target add ${TARGET}
  - cargo build  --target ${TARGET}  --features=${MCU}

script:
  - echo  target is ${TARGET}  features is ${MCU}  example is ${EG}
  - cargo build  --target ${TARGET}  --features ${MCU}  --example ${EG}
