[package]
name = "eg_stm_hal"
version = "0.1.0"
authors = ["Paul Gilbert <pdgilbert@users.noreply.github.com>"]
edition = "2018"
repository = "https://github.com/pdgilbert/eg_stm_hal"
#documentation = "https://"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# name = "whatever"  #lib name defaults to package name
# for most package the path to the lib would be
#path = "src/lib.rs"
# for the setup here that work if there is a link src/  --> ../../src/  but this works without the link
path = "../../src/lib.rs"
# A flag for enabling unit tests for this target. This is used by `cargo test`.
test = true

[[example]]
name = "test"
path = "examples/test.rs"
#required-features = ["rt"]

[[example]]
name = "blink"
path = "examples/blink.rs"

[[example]]
name = "serial_loopback_char"
path = "examples/serial_loopback_char.rs"

[[example]]
name = "serial_fmt"
path = "examples/serial_fmt.rs"

[[example]]
name = "serial_loopback_string"
path = "examples/serial_loopback_string.rs"

[[example]]
name = "echo_by_char"
path = "examples/echo_by_char.rs"

[[example]]
name = "serial_gps_rw"
path = "examples/serial_gps_rw.rs"

[[example]]
name = "serial_gps_rw_by_char"
path = "examples/serial_gps_rw_by_char.rs"

[package.metadata.docs.rs]
#features = ["stm32f103", "rt"]
features = ["stm32f103", "stm32f303", "stm32f411" ]
# NEED MORE HERE

[dependencies]
cortex-m = "0.6.0"
nb = "0.1.2"
cortex-m-rt = "0.6.8"
stm32f1 = "0.8.0"
stm32f3 = "0.8.0"
stm32f4 = "0.8.0"
#stm32l1 = "0.8.0"
as-slice = "0.1.2"
panic-halt = "0.2.0"

[dependencies.stm32f1xx-hal]
git = "https://github.com/stm32-rs/stm32f1xx-hal"
#fversion = "0.4.0"
features = ["stm32f103", "rt"]

[dependencies.stm32f3xx-hal]
git = "https://github.com/stm32-rs/stm32f3xx-hal"
version = "0.3.0"
features = ["stm32f303", "rt"]

#[dependencies.alt-stm32f30x-hal]
#version = "0.6.1"
#features = ["stm32f303", "rt"]

[dependencies.stm32f4xx-hal]
git = "https://github.com/stm32-rs/stm32f4xx-hal"
version = "0.6.0"
features = ["stm32f411", "rt"]

#[dependencies.stm32l1xx-hal]
#git = "https://github.com/stm32-rs/stm32l1xx-hal"
#version = "0.1.0"
#features = ["stm32l100", "stm32l151", "rt"]

[dependencies.void]
default-features = false
version = "1.0.2"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.embedded-hal]
version = "0.2.3"
features = ["unproven"]

[dev-dependencies]
panic-halt = "0.2.0"
panic-semihosting = "0.5.2"
panic-itm = "0.4.1"
cortex-m-rtfm = "0.4.3"
cortex-m-semihosting = "0.3.3"
enc28j60 = "0.2.1"
heapless = "0.4.3"
m = "0.1.1"
mfrc522 = "0.2.0"
serde_derive = "1.0.90"

[dev-dependencies.byteorder]
default-features = false
version = "1.3.1"

[dev-dependencies.cobs]
default-features = false
version = "0.1.4"

[dev-dependencies.crc16]
default-features = false
version = "0.4.0"

[dev-dependencies.either]
default-features = false
version = "1.5.2"

#[dev-dependencies.jnet]
#git = "https://github.com/japaric/jnet"
#rev = "df96b408049ca952ad7844d6552e87cf8fc18d2a"

#[dev-dependencies.motor-driver]
#git = "https://github.com/japaric/motor-driver"
#rev = "00c8b15223643090d69f1acfb8b7a7a43a440417"

#[dev-dependencies.mpu9250]
#git = "https://github.com/japaric/mpu9250"
#rev = "8f9ecad690093cb71c41301ca5e5705706150610"

[dev-dependencies.serde]
default-features = false
version = "1.0.90"

#[dev-dependencies.serde-json-core]
#git = "https://github.com/japaric/serde-json-core"
#rev = "6f12b77c1ffeae167989fe06e0d8b15978bd6d18"

[features]
device-selected = []
doc = []
stm32f100 = ["stm32f1/stm32f100", "stm32f1/rt", "device-selected"]
stm32f101 = ["stm32f1/stm32f101", "stm32f1/rt", "device-selected"]
stm32f103 = ["stm32f1/stm32f103", "stm32f1/rt", "device-selected"]
stm32f303 = ["stm32f3/stm32f303", "stm32f3/rt", "device-selected"]
stm32f411 = ["stm32f4/stm32f411", "stm32f4/rt", "device-selected"]
#stm32l100 = ["stm32l1/stm32l100", "stm32l1/rt", "device-selected"]
#stm32l151 = ["stm32l1/stm32l151", "stm32l1/rt", "device-selected"]

# Devices with 64 or 128 Kb ROM
medium = []
# Devices with 256 or 512 Kb ROM
high = ["medium"]
# Devices with 768 Kb ROM or more
xl = ["high"]

[profile.dev]
incremental = false
codegen-units = 1

[profile.release]
codegen-units = 1
debug = true
lto = true
